### PR TITLE
fix(datatable): fix sort parameters

### LINKED ISSUE #355: Fix DataTable sort method direction and key values
While the default DataTable `sort` method manages sort direction and header key values properly, the custom method is defined without these variables in scope.

https://github.com/IBM/carbon-components-svelte/blob/8a65e463a16a7dcc48166471d6dab6362cfe2b3e/src/DataTable/DataTable.svelte#L135-L136

We may directly pass the `a` and `b` params as a result of `itemA` and `itemB` values, respectively.

### PR DESCRIPTION
**Pull request by albertms10**
fixes #355

---

- fix(datatable): fix sort parameters

### CODE REVIEW

**Comment by metonym** [comment]
@albertms10  Could you add an example that adapts the existing ["Sortable" example](https://carbon-svelte.vercel.app/components/DataTable#sortable) that demonstrates the custom sort method?

**Comment by albertms10** [comment]
Something like using `dayjs` and `i18n` related dependencies:

```svelte
<script lang="ts">
  import { DataTable } from "carbon-components-svelte";
  import dayjs from "dayjs";
  import relativeTime from "dayjs/plugin/relativeTime";
  import { number } from "svelte-i18n";

  dayjs.extend(relativeTime); // for `dayjs().fromNow()` method

  const headers = [
    {
      key: "name",
      value: "Name",
    },
    {
      key: "quantity",
      value: "Quantity"
      display: (quantity) => $number(quantity, { format: "EUR" }),
    },
    {
      key: "date",
      value: "Date",
      display: (date) => dayjs(date).fromNow(),
      sort: (a, b) => (dayjs(a.date).isAfter(dayjs(b.date)) ? 1 : -1),
    },
  ];

  const rows = [
    {
      id: 1,
      name: "John",
      quantity: 157.89,
      date: "2020-10-21",
    }
  ];
</script>

<DataTable {headers} {rows} />
```

**Comment by metonym** [comment]
To avoid adding additional dependencies, can you simplify the example even further to omit dayjs, svelte-i18n?

**Comment by albertms10** [comment]
Ok, what about:

```svelte
<script lang="ts">
  import { DataTable } from "carbon-components-svelte";

  const headers = [
    {
      key: "name",
      value: "Name",
    },
    {
      key: "quantity",
      value: "Quantity",
      display: (quantity: number) => `${quantity} €`,
    },
    {
      key: "date",
      value: "Date",
      display: (date: string) => new Date(date).toLocaleString(),
      sort: (a: string, b: string) => (new Date(a) <= new Date(b) ? -1 : 1),
    },
  ];

  const rows = [
    {
      id: 1,
      name: "John",
      quantity: 157.89,
      date: "2020-10-21",
    }
  ];
</script>

<DataTable {headers} {rows} />
```

**Comment by metonym** [comment]
That works

**Comment by albertms10** [comment]
What do you think, @metonym, about the types that involve `rows` and `headers`? https://github.com/IBM/carbon-components-svelte/pull/356#issuecomment-715884784

**Comment by metonym** [comment]
@albertms10 For the TypeScript comment, I'm not sure how it would be automatically inferred without typing it. Would typing `headers` as a tuple work?

Something like:

```ts
const headers: [{key: "quantity", value: "Quantity", display: (quantity: number) => string;}] = [{
  key: "quantity",
  value: "Quantity",
  display: (quantity: number) => `${quantity} €`,
}]
```

**Review by metonym — APPROVED** [review]

**Comment by albertms10** [comment]
To get things properly organized, I opened a new issue (#364) to talk about TypeScript types definitions and let this issue close the way it should.

**Pull request merged**
