### PR TITLE
Update SideNavLink.svelte

### PR DESCRIPTION
**Pull request by DavidSedman**
The Icon throws as SSR error when used. This uses the same code as the HeaderGlobalAction which works with no errors

### CODE REVIEW

**Review by josefaidt — APPROVED** [review]
Hi @DavidSedman this looks good to me! @metonym any comments?

**Review by metonym — COMMENTED** [review]
There's a breaking change here.

The `icon` prop type is changed.

Which leads me to believe that the SSR error is caused because the Carbon icon is not passed to `icon.render`.

@DavidSedman 

How are you currently using it. Can you provide a repro for the error?

Have you tried this?

```svelte
<SideNavLink icon={{ render: Add16 }} />
```

**Comment by DavidSedman** [comment]
Hi @metonym,

I'm using it as follows:
```
<SideNavLink href="/" text="Home" icon="{Home16}" on:click={closeMenu} />
<SideNavLink href="/about" text="About MediaStudio Web" icon="{InformationSquare16}" on:click={closeMenu} />
<SideNavLink href="/logs" text="Application Logs" icon="{Terminal16}" on:click={closeMenu} />
```

Similar to the vercel ([UIShell header with utilities](https://carbon-svelte.vercel.app/components/UIShell#header-with-utilities)) sample for HeaderGlobalAction:
```
<HeaderGlobalAction aria-label="Settings" icon={SettingsAdjust20} />
``` 

If it should be: `<SideNavLink icon={{ render: Add16 }} />` as you said, there are inconsistencies between the documentation and how 'icon' is used across the components.

Error I'm getting is:
'''
Error: <svelte:component this={...}> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
    at validate_component (/src/__sapper__/dev/server/server.js:194:15)
    at /src/__sapper__/dev/server/server.js:1058:7
    at Object.$$render (/src/__sapper__/dev/server/server.js:212:22)
    at /src/__sapper__/dev/server/server.js:1274:59
    at Object.$$render (/src/__sapper__/dev/server/server.js:212:22)
    at Object.default (/src/__sapper__/dev/server/server.js:1926:71)
    at /src/__sapper__/dev/server/server.js:1239:103
    at Object.$$render (/src/__sapper__/dev/server/server.js:212:22)
    at Object.default (/src/__sapper__/dev/server/server.js:1925:72)
    at /src/__sapper__/dev/server/server.js:1233:288
'''

**Review by metonym — CHANGES_REQUESTED** [review]
@DavidSedman 

I think that making the `icon` prop consistent is the right move.

Could you apply this change to these files as well?

- HeaderActionLink
- SideNavMenu

and update the `icon` type

```diff
   /**
-   * Specify the icon props
-   * @type {{ render: import("carbon-icons-svelte").CarbonIcon; skeleton: boolean; }}
+  * Specify the icon from `carbon-icons-svelte` to render
+  * @type {typeof import("carbon-icons-svelte").CarbonIcon}
    */
   export let icon = undefined;
```

**Pull request closed without merging**
