### PR TITLE
feat: Component based UIShell

### PR DESCRIPTION
**Pull request by mfeitoza**
@metonym this is the first PR for the component based UIShell.

So I want to discuss the names of compoments (I fallow the Carbon Guidelines and React components).

I think could be:

```js
<UIShell>
  <GlobalHeader>
    <HeaderNav>
    </HeaderNav>
    <HeaderUtilities> // or actions?
      <HeaderAction />
    </HeaderUtilities>
  </GlobalHeader>
  <SideNav>
  </SideNav>
</UIShell>
```

### CODE REVIEW

**Comment by mfeitoza** [comment]
I will finish tomorrow!

**Comment by mfeitoza** [comment]
Done! Is ok "HeaderPanel.."?



From React implementation, I can work in all this variations?

**Comment by metonym** [comment]
Nice work, @mfeitoza

**Comment by metonym** [comment]
Released in [v0.4.0](https://github.com/IBM/carbon-components-svelte/blob/master/CHANGELOG.md#040---2020-04-18)

**Pull request merged**
