### PR TITLE
Add support for nested object fields in DataTable

### PR DESCRIPTION
**Pull request by alkanna**
I took the liberty to provide a way to access nested objects by a string path.
I also changed the way undefined items are handled : instead of showing up as "undefined" in the DataTable, the cells will simply be empty, which makes it so that it does not crash with the default sorting behaviour.

### CODE REVIEW

**Comment by alkanna** [comment]
@metonym Hey, could you take a look at this ?

**Comment by metonym** [comment]
Thanks for taking the time to put this PR together. Referencing #597, I agree that an undefined value should default to an empty string.

For the part about nested objects/arrays, could you provide a simple example?

**Comment by alkanna** [comment]
Hey, it's pretty straightforward.
Let's say we have this array of objects :
```javascript
[{
    id: 'a',
    name: 'Load Balancer 3',
    network: {
		protocol: "HTTP",
		port: 3000
	},
    rule: 'Round robin'
}, {
    id: 'b',
    name: 'Load Balancer 1',
    network: {
		protocol: "HTTP",
		port: 443
	},
    rule: 'Round robin'
}, {
    id: 'c',
    name: 'Load Balancer 2',
    network: {
		protocol: "HTTP",
		port: 80
	},
    rule: 'DNS delegation'
}]
```

Before, we could not access `network.protocol` in a `DataTable`, with this little PR, we can do so like this :

```html
<DataTable
  headers={[{ key: 'name', value: 'Name' }, { key: 'network.protocol', value: 'Protocol' }, { key: 'network.port', value: 'Port' }, { key: 'rule', value: 'Rule' }]}
  rows={}
/>
```

This would also work if `network` was an array (also works with indexes) and not an object :

```javascript
data = [{
    id: 'a',
    name: 'Load Balancer 3',
    network: ["HTTP", 3000],
    rule: 'Round robin'
}, {
    id: 'b',
    name: 'Load Balancer 1',
    network: ["HTTP", 443],
    rule: 'Round robin'
}];

console.log(resolvePath(data[0], "network.1", ""));
```

Output : 
```shell
$ node index.js 
3000
```

**Comment by alkanna** [comment]
If there is anything missing don't hesitate to point it out, like tests or documentation.

**Comment by metonym** [comment]
@alkanna I like that example. Could you add an example "Sortable with nested object values" to the doc site after the [Sortable with custom display and sort methods](https://github.com/IBM/carbon-components-svelte/blob/master/docs/src/pages/components/DataTable.svx#L612)?

**Comment by alkanna** [comment]
Hey @metonym, I added the example as requested.

**Review by metonym — APPROVED** [review]
Great work – excited to use this feature.

Also, this should close related issue #564

**Comment by metonym** [comment]
Published to NPM in [version 0.33.0](https://github.com/IBM/carbon-components-svelte/releases/tag/v0.33.0)

**Pull request merged**
