### PR TITLE
fix ComposedModal body classes, remove i10n locales from DatePicker

### PR DESCRIPTION
**Pull request by weaseldotro**
ComposedModal body classes were reversed in the code logic.
Removing i10n locales from Datepicker saves 41972 bytes from the total build bundle size. Also, I think they shouldn't be preinstalled, developers can add them depending on their app requirements.

### CODE REVIEW

**Comment by metonym** [comment]
I think that removing flatpickr as a direct dependency has its merits.

- Could you open a separate issue for flatpickr and keep this PR focused just on fixing the ComposedModal?
- Also, please merge the latest from the upstream master so the [deploy preview](https://vercel.com/carbon-svelte/carbon-components-svelte/h0dm6rnv3) can build

**Comment by weaseldotro** [comment]
> I think that removing flatpickr as a direct dependency has its merits.
> 
>     * Could you open a separate issue for flatpickr and keep this PR focused just on fixing the ComposedModal?
> 
>     * Also, please merge the latest from the upstream master so the [deploy preview](https://vercel.com/carbon-svelte/carbon-components-svelte/h0dm6rnv3) can build

Sorry but I'm a bit of a beginner with github and git collaboration, I have no idea how to do that and I'm currently too lazy to search how :disappointed:  I'll just close this pull request, refork, commit and open another pull request :grin:

**Comment by metonym** [comment]
@weaseldotro No problem, you're doing great. We really appreciate your contributions to this library, as we barrel ahead towards a v1 release.

Generally, focused PRs are faster to review and merge. For example, it's easier to merge 10 PRs that are focused on individual issues than 1 giant PR that deals with 10 separate issues.

For the development flow, if I'm contributing to another project, I typically:

1) Fork the project
2) Switch to `master` on the fork and make sure I've pulled that latest upstream changes from `master`
3) Create a branch off of that
4) Submit PR
5) Delete branch and start at step 2

**Comment by weaseldotro** [comment]
Thanks for the advices. Should I create a PR with the removing of the i10n from DatePicker, or open an issue regarding this?

**Comment by metonym** [comment]
First open an issue for discussion

**Pull request closed without merging**
